/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package j2sp0126;

import java.awt.Color;

/**
 *
 * @author ACER
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        rdbRed = new javax.swing.JRadioButton();
        rdbBlue = new javax.swing.JRadioButton();
        rdbGreen = new javax.swing.JRadioButton();
        rdbBlack = new javax.swing.JRadioButton();
        txtDisplay = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGroup1.add(rdbRed);
        rdbRed.setText("Red");
        rdbRed.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rdbRedStateChanged(evt);
            }
        });
        rdbRed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbRedActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdbBlue);
        rdbBlue.setText("Blue");
        rdbBlue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbBlueActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdbGreen);
        rdbGreen.setText("Green");
        rdbGreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbGreenActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdbBlack);
        rdbBlack.setText("Black");
        rdbBlack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbBlackActionPerformed(evt);
            }
        });

        txtDisplay.setForeground(new java.awt.Color(255, 255, 255));
        txtDisplay.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtDisplay, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdbBlue)
                    .addComponent(rdbGreen)
                    .addComponent(rdbRed)
                    .addComponent(rdbBlack))
                .addContainerGap(148, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(rdbRed)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdbBlue)
                .addGap(8, 8, 8)
                .addComponent(rdbGreen)
                .addGap(18, 18, 18)
                .addComponent(rdbBlack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(txtDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdbRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbRedActionPerformed
         txtDisplay.setBackground(Color.RED);
         txtDisplay.setText("Red is selected");
    }//GEN-LAST:event_rdbRedActionPerformed

    private void rdbRedStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rdbRedStateChanged
    
    }//GEN-LAST:event_rdbRedStateChanged

    private void rdbBlueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbBlueActionPerformed
       txtDisplay.setBackground(Color.BLUE);
         txtDisplay.setText("Blue is selected");
    }//GEN-LAST:event_rdbBlueActionPerformed

    private void rdbGreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbGreenActionPerformed
       txtDisplay.setBackground(Color.GREEN);
         txtDisplay.setText("Green is selected");
    }//GEN-LAST:event_rdbGreenActionPerformed

    private void rdbBlackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbBlackActionPerformed
        txtDisplay.setBackground(Color.BLACK);
         txtDisplay.setText("Black is selected");
    }//GEN-LAST:event_rdbBlackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JRadioButton rdbBlack;
    private javax.swing.JRadioButton rdbBlue;
    private javax.swing.JRadioButton rdbGreen;
    private javax.swing.JRadioButton rdbRed;
    private javax.swing.JTextField txtDisplay;
    // End of variables declaration//GEN-END:variables
}
